spring:
  application:
    name: uride-eureka-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 90
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF